#!/bin/bash

# Quick Commands Reference
# Save this as reference for frequent commands

echo "🚀 Microsoft Entra AD Authentication - Quick Commands Reference"
echo "=================================================================="
echo ""
echo "📦 Project Setup Commands:"
echo "  npm install                # Install dependencies (run once)"
echo "  npm run dev               # Start development server"
echo "  npm run build             # Build for production"
echo "  npm run preview           # Preview production build"
echo "  npm run lint              # Run ESLint"
echo ""
echo "📁 Useful Development Commands:"
echo "  ls src/                  # View source structure"
echo "  cat .env.example         # View environment template"
echo "  cat package.json         # View dependencies"
echo ""
echo "🔍 Debugging Commands:"
echo "  npm run dev              # Check for errors in console"
echo "  npm run build            # Check for build errors"
echo ""
echo "📖 Documentation Files:"
echo "  cat README.md                   # Project overview"
echo "  cat docs/REFERENCE.md                # Code examples"
echo "  cat docs/ARCHITECTURE.md             # Diagrams"
echo ""
echo "✅ Verification Steps:"
echo "  npm run lint              # Check code quality"
echo "  npm run build             # Verify build works"
echo "  npm run dev               # Test dev server"
echo ""
echo "📝 Configuration:"
echo "  Copy .env.example to .env.local"
echo "  Edit .env.local with your Azure credentials"
echo ""
echo "🎯 Next Steps:"
echo "  1. npm install"
echo "  2. cp .env.example .env.local"
echo "  3. Edit .env.local"
echo "  4. npm run dev"
echo "  5. Open http://localhost:5173/"
echo ""
echo "❓ Need Help?"
echo "  - Read the documentation files"
echo "  - Check REFERENCE.md for troubleshooting"
echo "  - Review source code comments"
echo ""
